---
- name: Setup archlinux
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
    gpg_pass: "{{ lookup('env', 'GPG_PASS') }}"
    zsh_custom: "{{ home }}/.oh-my-zsh/custom"
    gpg_source_key: "./vault/gpg/secret.asc"
    ssh_source_key: "./vault/ssh/id_rsa"
    ssh_dest_key: "{{ home }}/.ssh/id_rsa"
  hosts: localhost
  tasks:
    - name: Start Pacman Key
      ansible.builtin.import_tasks:
        file: tasks/pacman/key-init.yaml
      tags:
        - install
        - pacman

    - name: Add Pacman Multilib
      ansible.builtin.import_tasks:
        file: tasks/pacman/multilib-repo.yaml
      tags:
        - install
        - pacman

    - name: Pacman Update
      ansible.builtin.import_tasks:
        file: tasks/pacman/update.yaml
      tags:
        - install
        - pacman

    - name: Include core-utils tasks
      ansible.builtin.import_tasks:
        file: tasks/core-utils.yaml
      tags:
        - install
        - core-utils

    - name: Include aur tasks
      ansible.builtin.import_tasks:
        file: tasks/aur.yaml
      tags:
        - install
        - aur

    - name: Include extra-utils tasks
      ansible.builtin.import_tasks:
        file: tasks/extra-utils.yaml
      tags:
        - install
        - extra-utils

    - name: Include zsh tasks
      ansible.builtin.import_tasks:
        file: tasks/zsh.yaml
      tags:
        - install
        - zsh

    - name: Include fonts tasks
      ansible.builtin.import_tasks:
        file: tasks/fonts.yaml
      tags:
        - install
        - fonts

    - name: Include file manager tasks
      ansible.builtin.import_tasks:
        file: tasks/file-manager.yaml
      tags:
        - install
        - file-manager

    - name: Include sound tasks
      ansible.builtin.import_tasks:
        file: tasks/sound.yaml
      tags:
        - install
        - sound

    - name: Include bluetooth tasks
      ansible.builtin.import_tasks:
        file: tasks/bluetooth.yaml
      tags:
        - install
        - bluetooth

    - name: Include vpn tasks
      ansible.builtin.import_tasks:
        file: tasks/vpn.yaml
      tags:
        - install
        - vpn

    - name: Include ssh tasks
      ansible.builtin.import_tasks:
        file: tasks/ssh.yaml
      tags:
        - install
        - keys
        - ssh

    - name: Include gpg tasks
      ansible.builtin.import_tasks:
        file: tasks/gpg.yaml
      tags:
        - install
        - keys
        - gpg

    - name: Include Oh-My-Zsh tasks
      ansible.builtin.import_tasks:
        file: tasks/omz.yaml
      tags:
        - install
        - omz
