---
- name: Install core utils tools
  community.general.pacman:
    name:
      - make
      - less
      - man-pages
      - man-db
      - curl
      - wget
      - openssl
      - openssh
      - gnupg
      - git
      - vi
      - vim
      - htop
    state: present
  become: true
