---
- name: Install extra-utils packages
  become: true
  kewlfft.aur.aur:
    name:
      - jq
      - expac
      - acpid
    use: yay
    state: present
  changed_when: false

- name: Make sure acpid is enabled
  ansible.builtin.systemd_service:
    enabled: true
    state: started
    name: acpid
  become: true

- name: Make sure systemd-timesyncd is enabled
  ansible.builtin.systemd_service:
    enabled: true
    state: started
    name: systemd-timesyncd.service
  become: true

- name: Check for SSD storages
  ansible.builtin.command: cat /sys/block/sda/queue/rotational /sys/block/nvme0n1/queue/rotational # TODO: pass path as var
  register: is_ssd_output
  changed_when: false

- name: Make sure fstrim timer is enabled when there is a SSD storage
  ansible.builtin.systemd_service:
    enabled: true
    state: started
    name: fstrim.timer
  when: "'0' in is_ssd_output.stdout"
  become: true
