---
- name: Install fonts packages
  kewlfft.aur.aur:
    name:
      - ttf-fira-code
      - ttf-fira-mono
      - ttf-firacode-nerd
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-extra
    use: yay
    state: present
  changed_when: false
