---
- name: Install fonts packages
  become: true
  kewlfft.aur.aur:
    name:
      - ttf-dejavu
      - ttf-fira-code
      - ttf-fira-mono
      - ttf-firacode-nerd
      - ttf-jetbrains-mono-nerd
      - ttf-meslo-nerd-font-powerlevel10k
      - ttf-sarasa-gothic
      - ttf-ubuntu-font-family
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-extra
    use: yay
    state: present
  changed_when: false
