---
- name: Install ZSH
  become: true
  kewlfft.aur.aur:
    name:
      - zsh
    use: yay
    state: present
  changed_when: false

- name: Change $USER shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /bin/zsh

- name: Prevent zsh new user function
  ansible.builtin.copy:
    mode: "0644"
    owner: "{{ user }}"
    dest: "{{ home }}/.zshrc"
    content: |
      # Prevent zsh new user function
